
set(target "MainWindowModule")
set(working_dir "C:/Users/User/qgroundcontrol/src/UI")
set(src_and_dest_list
    "C:/Users/User/qgroundcontrol/src/UI/MainWindow.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/MainWindow.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_GPS.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_GPS.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_GPS_Settings.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_GPS_Settings.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_Battery.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_Battery.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_UcusRejimi.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_UcusRejimi.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_UcusRejimi_Settings.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_UcusRejimi_Settings.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_RCSignal.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_RCSignal.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_RCSignal_Settings.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_RCSignal_Settings.qml"
    "C:/Users/User/qgroundcontrol/src/UI/TopStatusPanel_Battery_Settings.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/TopStatusPanel_Battery_Settings.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_AparatQurgusu.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_AparatQurgusu.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Radio.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Radio.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_FlightMode.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_FlightMode.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Sensors.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Sensors.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Sensors_Accelerometer.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Sensors_Accelerometer.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Enerji.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Enerji.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Motors.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Motors.qml"
    "C:/Users/User/qgroundcontrol/src/UI/SideMenu_Tehlukesizlik.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/SideMenu_Tehlukesizlik.qml"
    "C:/Users/User/qgroundcontrol/src/UI/Side_Parameter.qml"
    "C:/Users/User/qgroundcontrol/build-mingw/qml/QGroundControl/MainWindow/Side_Parameter.qml"

)
set(timestamp_file "C:/Users/User/qgroundcontrol/build-mingw/src/UI/.qt/MainWindowModule_qml.txt")
