# CMake generated Testfile for 
# Source directory: C:/Users/User/qgroundcontrol/test
# Build directory: C:/Users/User/qgroundcontrol/build-msvc/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ADSBTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ADSBTest")
set_tests_properties([=[ADSBTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;76;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[ExifParserTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ExifParserTest")
set_tests_properties([=[ExifParserTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;79;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[LogDownloadTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:LogDownloadTest")
set_tests_properties([=[LogDownloadTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;81;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[PX4LogParserTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:PX4LogParserTest")
set_tests_properties([=[PX4LogParserTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;83;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[QGCCameraManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:QGCCameraManagerTest")
set_tests_properties([=[QGCCameraManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;90;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[QGCSerialPortInfoTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:QGCSerialPortInfoTest")
set_tests_properties([=[QGCSerialPortInfoTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;93;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[FactSystemTestGeneric]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:FactSystemTestGeneric")
set_tests_properties([=[FactSystemTestGeneric]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;96;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[FactSystemTestPX4]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:FactSystemTestPX4")
set_tests_properties([=[FactSystemTestPX4]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;97;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[ParameterManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ParameterManagerTest")
set_tests_properties([=[ParameterManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;98;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[FollowMeTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:FollowMeTest")
set_tests_properties([=[FollowMeTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;101;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[GpsTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:GpsTest")
set_tests_properties([=[GpsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;104;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[StatusTextHandlerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:StatusTextHandlerTest")
set_tests_properties([=[StatusTextHandlerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;107;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[SigningTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:SigningTest")
set_tests_properties([=[SigningTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;108;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[CameraCalcTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:CameraCalcTest")
set_tests_properties([=[CameraCalcTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;111;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[CameraSectionTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:CameraSectionTest")
set_tests_properties([=[CameraSectionTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;112;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[CorridorScanComplexItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:CorridorScanComplexItemTest")
set_tests_properties([=[CorridorScanComplexItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;113;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionCommandTreeTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionCommandTreeTest")
set_tests_properties([=[MissionCommandTreeTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;117;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionControllerManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionControllerManagerTest")
set_tests_properties([=[MissionControllerManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;118;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionControllerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionControllerTest")
set_tests_properties([=[MissionControllerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;119;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionItemTest")
set_tests_properties([=[MissionItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;120;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionManagerTest")
set_tests_properties([=[MissionManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;121;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MissionSettingsTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MissionSettingsTest")
set_tests_properties([=[MissionSettingsTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;122;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[PlanMasterControllerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:PlanMasterControllerTest")
set_tests_properties([=[PlanMasterControllerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;123;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[QGCMapPolygonTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:QGCMapPolygonTest")
set_tests_properties([=[QGCMapPolygonTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;124;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[QGCMapPolylineTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:QGCMapPolylineTest")
set_tests_properties([=[QGCMapPolylineTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;125;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[SimpleMissionItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:SimpleMissionItemTest")
set_tests_properties([=[SimpleMissionItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;127;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[SpeedSectionTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:SpeedSectionTest")
set_tests_properties([=[SpeedSectionTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;128;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[StructureScanComplexItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:StructureScanComplexItemTest")
set_tests_properties([=[StructureScanComplexItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;129;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[SurveyComplexItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:SurveyComplexItemTest")
set_tests_properties([=[SurveyComplexItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;130;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[TransectStyleComplexItemTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:TransectStyleComplexItemTest")
set_tests_properties([=[TransectStyleComplexItemTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;131;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[TerrainQueryTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:TerrainQueryTest")
set_tests_properties([=[TerrainQueryTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;140;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[TerrainTileTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:TerrainTileTest")
set_tests_properties([=[TerrainTileTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;141;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[AudioOutputTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:AudioOutputTest")
set_tests_properties([=[AudioOutputTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;145;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[DecompressionTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:DecompressionTest")
set_tests_properties([=[DecompressionTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;147;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[QGCFileDownloadTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:QGCFileDownloadTest")
set_tests_properties([=[QGCFileDownloadTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;149;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[GeoTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:GeoTest")
set_tests_properties([=[GeoTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;151;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[ShapeTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ShapeTest")
set_tests_properties([=[ShapeTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;153;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[ComponentInformationCacheTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ComponentInformationCacheTest")
set_tests_properties([=[ComponentInformationCacheTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;157;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[ComponentInformationTranslationTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:ComponentInformationTranslationTest")
set_tests_properties([=[ComponentInformationTranslationTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;158;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[FTPManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:FTPManagerTest")
set_tests_properties([=[FTPManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;159;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[MAVLinkLogManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:MAVLinkLogManagerTest")
set_tests_properties([=[MAVLinkLogManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;161;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
add_test([=[VehicleLinkManagerTest]=] "C:/Users/User/qgroundcontrol/build-msvc/Debug/QGroundControl.exe" "--unittest:VehicleLinkManagerTest")
set_tests_properties([=[VehicleLinkManagerTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/qgroundcontrol/test/CMakeLists.txt;68;add_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;165;add_qgc_test;C:/Users/User/qgroundcontrol/test/CMakeLists.txt;0;")
subdirs("ADSB")
subdirs("AnalyzeView")
subdirs("Camera")
subdirs("Comms")
subdirs("FactSystem")
subdirs("FollowMe")
subdirs("GPS")
subdirs("MAVLink")
subdirs("MissionManager")
subdirs("qgcunittest")
subdirs("Terrain")
subdirs("Utilities")
subdirs("Vehicle")
